/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tercerparcial;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author keiinerp
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    RegistrarUsuari registrarUsuarioVentana;
    ArrayList<Cliente> listaClientes;
    String nombre = null, identificacion = null;

    public Login() {
        initComponents();
        listaClientes = Archivos.leerCliente();
        logueado=0;
        if (listaClientes == null) {
            Cliente cliente = new Cliente();
            cliente.setNombreUsuario("KEVIN");
            cliente.setNombreUsuario("admin");
            cliente.setClave("123");
            cliente.setIdentificacion("11919192913");
            listaClientes.add(cliente);
            Archivos.escribirCliente(listaClientes);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        claveText = new javax.swing.JPasswordField();
        registroTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UserText = new javax.swing.JTextField();
        entrarBoton = new javax.swing.JButton();
        registrarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        claveText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveTextActionPerformed(evt);
            }
        });

        registroTitulo.setText("No tienes un usuario Regístrate");
        registroTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registroTituloMouseClicked(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bienvenido");

        jLabel3.setText("Usuario:");

        jLabel4.setText("Contraseña:");

        entrarBoton.setText("Entrar");
        entrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarBotonActionPerformed(evt);
            }
        });

        registrarBoton.setText("Registrar");
        registrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(registroTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(registrarBoton)
                        .addGap(0, 134, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UserText, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(claveText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(entrarBoton)
                .addGap(161, 161, 161))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(UserText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(claveText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(entrarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registroTitulo)
                    .addComponent(registrarBoton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void claveTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveTextActionPerformed

    private void registroTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroTituloMouseClicked

    }//GEN-LAST:event_registroTituloMouseClicked

    private void entrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarBotonActionPerformed
        entrar();
    }//GEN-LAST:event_entrarBotonActionPerformed
    public Cliente clienteEncontrado;
public static String nombreCliente;
public static String identificacionCliente;
    private void entrar() {
        int registrado = 0;
        for (Cliente p : listaClientes) {
            if (p.getNombreUsuario().equals(UserText.getText()) && p.getClave().equals(claveText.getText())) {
                registrado = 1;
                nombre = p.getNombreCliente();
                identificacion = p.getIdentificacion();
                nombreCliente=nombre;
                identificacionCliente=identificacion;
            }
        }
        if (registrado == 1) {
            JOptionPane.showMessageDialog(this, "Bienvenido " + nombre);
            dispose();            
            logueado=1;
        } else {
            JOptionPane.showMessageDialog(null, "Usuario y/o Contraseña incorrectos");
        }
    }
public static int logueado=0;
  
    private void registrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBotonActionPerformed
        String pass = JOptionPane.showInputDialog(this, "Ingrese el codigo administrativo");
        try {
            if (pass.equals("1141")) {
                registrarUsuarioVentana = new RegistrarUsuari();
                registrarUsuarioVentana.setVisible(true);
                registro = RegistrarUsuari.registro;
                if (registro == 1) {
                    listaClientes = Archivos.leerCliente();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Pase incorrecto, por favor verifique");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_registrarBotonActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField UserText;
    private javax.swing.JPasswordField claveText;
    private javax.swing.JButton entrarBoton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton registrarBoton;
    private javax.swing.JLabel registroTitulo;
    // End of variables declaration//GEN-END:variables
public int registro;
}
